version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/raspberrypi4-homeassistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 1m
      timeout: 10s
      retries: 3
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb 
    image: mariadb:latest
    volumes:
      - ./mariadb/config:/etc/mysql/conf.d
      - ./mraiadb/data:/var/lib/mysql
    restart: unless-stopped
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeassistant
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: homeassistant



